version: '3'
services:
  react-ui:
    build:
      context: ./
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
       - .:/usr/src/app/my-app
       - /usr/src/app/my-app/node_modules